# Generated by Django 4.2.7 on 2025-10-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='total_loaded',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
