# Generated by Django 4.2.7 on 2025-10-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_voucher_total_loaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
