# Generated by Django 4.2.7 on 2025-10-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_voucher_deleted_at_voucher_is_deleted'),
    ]

    operations = [
    ]
